spring:
  datasource:
    url: jdbc:postgresql://postgres.zpdqzuaifderypebuqwo:3xp3ns3-tr4ck3r@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres
    password: sua_senha_aqui
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Deixa o Flyway cuidar de criar as tabelas
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration